---

- name: jenkins restart
  service: name=jenkins state=restarted
  sudo: yes
  
- name: jenkins restart
  wait_for: host="{{ jenkins_http_host }}" port="{{ jenkins_http_port}}" timeout=30

- name: jenkins restart
  shell: curl --head --silent http://{{ jenkins_http_host }}:{{ jenkins_http_port }}{{ jenkins_prefix }}/cli/
  delay: 10
  retries: 12
  until: result.stdout.find("200 OK") != -1
  register: result
  changed_when: False

- name: jenkins update jobs
  shell: curl --head --silent http://{{ jenkins_http_host }}:{{ jenkins_http_port }}{{ jenkins_prefix }}/cli/
  delay: 10
  retries: 12
  until: result.stdout.find("200 OK") != -1
  register: result
  changed_when: False

- name: jenkins update jobs
  wait_for: host="{{ jenkins_http_host }}" port="{{ jenkins_http_port}}" timeout=30

- name: jenkins update jobs
  command: "{{jenkins_home}}/jobs/job.sh {{item.item.name}}"
  sudo_user: "{{ jenkins_user }}"
  when: item.changed
  with_items: jenkins_jobs_changed.results

- name: jenkins reload configuration
  command: java -jar {{jenkins_home}}/jenkins-cli.jar {{jenkins_cli_extra_opts}} -s http://{{ jenkins_http_host }}:{{ jenkins_http_port }}{{jenkins_prefix}} reload-configuration
  sudo_user: "{{ jenkins_user }}"

- name: nginx reload
  service: name=nginx state=reloaded
  sudo: yes
  
- name: apache restart
  service: name=apache2 state=restarted
  sudo: yes
  
